services:
  api-service:
    build:
      context: .
      dockerfile: services/api_service/Dockerfile
    env_file: .env
    ports:
      - "8080:8080"

  data-syncer:
    build:
      context: .
      dockerfile: services/data_syncer/Dockerfile
    env_file: .env

  strategy-engine:
    build:
      context: .
      dockerfile: services/strategy_engine/Dockerfile
    env_file: .env

volumes:
  mariadb_data:
